// assignment3/src/app/parent/parent.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { AppService } from '../app.service';
@Component({
  selector: 'app-parent',
  templateUrl: './parent.component.html',
  styleUrls: ['./parent.component.css']
})
export class ParentComponent implements OnInit {

  constructor(private appService: AppService) { }
demoData:any;
selectedValue:any;
 ngOnInit(): void {
  this.appService.getData().subscribe((data)=>{
this.demoData=data;
  });
  }
recieveMessage($event:any){
this.selectedValue=$event
this.sortData()
}

sortData()
{
  if(this.selectedValue==1)
  {
this.demoData.sort((a:any, b:any)=>(a.name>b.name) ? 1:-1)
  }
  if(this.selectedValue==2)
  {
this.demoData.sort((a:any,b:any)=>(new Date(a.birthDate).valueOf()-new Date(b.birthDate).valueOf()))
  }
}

}

<br>
<h3>Assignment3</h3>
<h4>List of users</h4>
<app-child (messageFromChild)="recieveMessage($event)"></app-child>
<div *ngIf="demoData?.length>0">
<table style="width:75%">
<thead>
<tr>
<th>Id</th>
<th>Name</th>
<th>Date of birth</th>
</tr>
</thead>
<tbody>
<tr *ngFor="let data of demoData;">
<td>{{data.id}}</td>
<td>{{data.name}}</td>
<td>{{data.birthDate}}</td>
</tr>
</tbody>
</table>
</div>

// assignment3-react/src/Parent.js
import React, { Component } from 'react';
import jsonData from './data.json';
import './Parent.css';
import Child from './Child.js';
export default class Parent extends Component {
    constructor(props)
    {
        super(props)
    }
  render() {

    if(this.props.value==1)
    {
        jsonData.sort((a, b)=>(a.name>b.name) ? 1:-1)
    }
    if(this.props.value==2)
    {
        jsonData.sort((a,b)=>(new Date(a.birthDate).valueOf()-new Date(b.birthDate).valueOf()))
    }
    return <div>      
<>
<br></br>
        <table >
          <thead>
            <tr>
              <th>Name</th>
              <th>Birth Date</th>
            </tr>
          </thead>
          <tbody>
            {
              jsonData.map(val => {
                return (
                  <tr key={val.id}>
                    <td>{val.name}</td>
                    <td>{val.birthDate}</td>
                  </tr>
                );
              })}
          </tbody>
        </table>
    </>


    </div>;
  }
}
