// assignment1-react/src/Components/Currency.js
import { getAllByTestId } from '@testing-library/react';
import React, {useState} from 'react'

export default function Currency() { 
const[inputVal,setData]=useState(null)
const[toSelect,toSetSelects]=useState(1);
const[fromSelect,fromSetSelects]=useState(4);
const[result,setResult]=useState();
 function getData(val)
{
    setData(val.target.value)
}
function buttonClicked()
{  
if(toSelect==1 && fromSelect==4)
{
   let inrCur=inputVal
   setResult(inrCur)
}
if(toSelect==1 && fromSelect==5)
{
let usdCur=inputVal* 0.013;
setResult(usdCur)
}

if(toSelect==1 && fromSelect==6)
{
let eurCur=inputVal*0.012
setResult(eurCur)
}

if(toSelect==2 && fromSelect==4)
{
let inrCur=inputVal*74.42
setResult(inrCur)
}
if(toSelect==2 && fromSelect==5)
{
let usdCur=inputVal
setResult(usdCur)
}
if(toSelect==2 && fromSelect==6)
{
let eurCur=inputVal*0.88
setResult(eurCur)
}
if(toSelect==3 && fromSelect==4)
{
var inrCur=inputVal*84.83
setResult(inrCur)
}
if(toSelect==3 && fromSelect==5)
{
var usdCur=inputVal*1.14
setResult(usdCur)
}
if(toSelect==3 && fromSelect==6)
{
var eurCur=inputVal
setResult(eurCur)
}
}

    return (
        <div className='App'>
           
            <h1> Currency Converter</h1>
            <br></br>
            <h3>Enter a value</h3>
            <input type="text" onChange={getData}/>
            <br></br><br></br>
            <select id="to" value={toSelect} onChange={e=>toSetSelects(e.target.value)}>
            <option value="1"> INR </option>
            <option value="2"> USD </option>
            <option value="3"> EUR </option>
            </select>
            &nbsp;&nbsp;&nbsp;&nbsp;
            <select id="from" value={fromSelect} onChange={r=>fromSetSelects(r.target.value)}> 
            <option value="4"> INR </option>
            <option value="5"> USD </option>
            <option value="6"> EUR </option>
            </select>
            <br></br><br></br>
            <button onClick={buttonClicked}>Convert Currency !</button>
            <br></br>
            <h4>Converted Value:</h4>
            <p>{result}</p>
        </div>
    )
}

// currency-converter/src/app/currency/currency.component.ts
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Input } from '@angular/core';

@Component({
  selector: 'app-currency',
  templateUrl: './currency.component.html',
  styleUrls: ['./currency.component.css']
})
export class CurrencyComponent implements OnInit {
inputValue: number=0;
toGroup:any;
fromGroup:any;
outputDivision:number=0;
isHidden:boolean=true;
  constructor() { }

  ngOnInit(): void {
  }
clickEve()
{  
if(this.fromGroup==1 && this.toGroup==4)
{
  let indCur=this.inputValue;
  this.outputDivision=indCur;
  this.isHidden=false;
}

if(this.fromGroup==1 && this.toGroup==5)
{
let usdCur=this.inputValue*0.013;
this.outputDivision=usdCur;
this.isHidden=false;
}

if(this.fromGroup==1 && this.toGroup==6)
{
  let eurCur=this.inputValue*0.012;
  this.outputDivision=eurCur;
  this.isHidden=false;
}



if(this.fromGroup==2 && this.toGroup==4)
{
  let indCur=this.inputValue*74.15;
  this.outputDivision=indCur;
  this.isHidden=false;
}

if(this.fromGroup==2 && this.toGroup==5)
{
let usdCur=this.inputValue;
this.outputDivision=usdCur;
this.isHidden=false;
}

if(this.fromGroup==2 && this.toGroup==6)
{
  let eurCur=this.inputValue*0.88;
  this.outputDivision=eurCur;
  this.isHidden=false;
}


if(this.fromGroup==3 && this.toGroup==4)
{
  let indCur=this.inputValue*84.57;
  this.outputDivision=indCur;
  this.isHidden=false;
}

if(this.fromGroup==3 && this.toGroup==5)
{
let usdCur=this.inputValue*1.14;
this.outputDivision=usdCur;
this.isHidden=false;
}

if(this.fromGroup==3 && this.toGroup==6)
{
  let eurCur=this.inputValue;
  this.outputDivision=eurCur;
  this.isHidden=false;
}

}
}

<h1> Currency Converter</h1>
Enter a value <br>
<input type="text" [(ngModel)]="inputValue"> <br><br>

<select id="from" [(ngModel)]="fromGroup">
<option value=1>INR</option>
<option value=2>USD</option>
<option value=3>EUR</option>
</select>
&nbsp;&nbsp;&nbsp;
<select id="to" [(ngModel)]="toGroup">
     <option value=4>INR</option>
    <option value=5>USD</option>
    <option value=6>EUR</option>
</select>
<br><br>
<button (click)="clickEve()">Convert Currency</button><br><br>
<div [hidden]="isHidden" [innerHTML]="outputDivision"></div>
